name: enum_bit_vector
description: Datatype storing a set of enum values as a 64-bit integer
homepage: https://github.com/tadeohepperle/enum_bit_vector
repository: https://github.com/tadeohepperle/enum_bit_vector
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.21.0
